# Generated by Django 5.2.3 on 2025-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact', models.CharField(max_length=150, verbose_name='Контакт')),
                ('goal', models.TextField(blank=True, verbose_name='Цель/Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
